[package]
name = "ws"
description = "A simple command-line webserver utility"
authors = ["Thatguyjs"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
ctrlc = "3.4.0"
