[package]
name = "ws"
authors = ["Thatguyjs"]
version = "0.3.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
clap = { version = "4.3.19", features = ["derive"] }
percent-encoding = "2.3.0"
tokio = { version = "1.29.1", features = ["full"] }
tower = "0.4.13"
