[package]
name = "ws"
description = "A simple command-line webserver utility"
authors = ["Thatguyjs"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
ctrlc = "3.2.0"
