[package]
name = "ws"
authors = ["Thatguyjs"]
version = "0.7.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["cargo"] }
httparse = "1.8.0"
percent-encoding = "2.3.0"
polling = "2.8.0"
